spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:demo_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update   # création / mise à jour automatique des tables
    show-sql: true       # affichage des requêtes SQL pour debug
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

# Swagger / OpenAPI activé uniquement en dev
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Logging dev plus détaillé
logging:
  level:
    root: DEBUG
